name: Auto Capture Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  actions: write

jobs:
  screenshot_job:
    runs-on: ubuntu-latest
    environment: CAPTURE

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # ✅ 여기 추가
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo rm -f /usr/bin/chromedriver || true

      - name: Install dependencies
        run: |
          pip install selenium requests   # 👉 webdriver-manager 제거

      - name: Run Python Script
        env:
          UPLOAD_URL: ${{ secrets.UPLOAD_URL }}
          TARGET_URL: ${{ secrets.TARGET_URL }}
        run: python capture_script.py
        

