name: Auto Capture Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'  # 0분 간격 (안정적으로 사용)

jobs:
  screenshot_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager requests

      - name: Run Python Script
        run: python capture_script.py
