name: Auto Capture Workflow

on:
  workflow_dispatch: # 버튼 눌러서 수동 실행 가능하게 함
  schedule:
    - cron: '*/10 * * * *' # 매 시간 정각에 실행

jobs:
  screenshot_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Run Python Script
        run: python capture_script.py # 위에서 만든 파일명과 똑같아야 함!

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-screenshots
          path: screenshots/
